import re


COMPANY_STOPWORDS = {
    "FACTURA", "FACTURA ELECTRONICA", "FACTURA ELECTRÓNICA", "CUFE", "CUDE",
    "CLIENTE", "ADQUIRIENTE", "COMPRADOR", "SEÑORES", "FECHA", "VENCIMIENTO",
    "MONEDA", "TRM", "TOTAL", "SUBTOTAL", "IVA", "BASE GRAVABLE", "VALOR TOTAL",
    "FORMA DE PAGO", "MEDIO DE PAGO", "NUMERO DE FACTURA", "NÚMERO DE FACTURA",
    "NO.", "NIT", "N.I.T", "DIRECCIÓN", "DIRECCION", "CIUDAD", "TEL", "TELÉFONO",
    "PBX", "RESPONSABLE DE IVA", "GENERADO POR", "GENERATED BY", "SIGNATURE",
    "SOFTWARE", "GOSOCKET", "SOUTH CONSULTING", "PWC", "INFORME DEL REVISOR",
    "REVISOR FISCAL", "CONTADOR", "REPRESENTANTE LEGAL",
}


def clean_value(value):
    if not value:
        return None
    value = str(value).strip()
    value = re.sub(r"\s+", " ", value)
    return value or None


def normalize_text(value: str | None) -> str:
    if not value:
        return ""
    return re.sub(r"\s+", " ", str(value)).strip().upper()


def compact_digits(value: str | None) -> str:
    if not value:
        return ""
    return re.sub(r"[^\d]", "", str(value))


def extract_emails(text: str) -> list[str]:
    matches = re.findall(r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}", text or "", re.IGNORECASE)
    cleaned = []
    for match in matches:
        value = clean_value(match)
        if value and value not in cleaned:
            cleaned.append(value)
    return cleaned


def extract_nits(text: str) -> list[str]:
    patterns = [
        r"(?:NIT|N\.I\.T\.|NIT\.|NO\.?\s*IDENT\.?\s*FISCAL|IDENTIFICACION FISCAL|IDENTIFICACIÓN FISCAL)\s*[:#\-]?\s*([0-9.\- ]{8,20})",
        r"(?:N[uú]mero de Identificaci[oó]n y/o NIT)\s*[:\-]?\s*([0-9.\- ]{8,20})",
        r"(?:No\.?\s*Ident\.?\s*Fiscal)\s*[:\-]?\s*([0-9.\- ]{8,20})",
    ]

    cleaned = []
    for pattern in patterns:
        for match in re.findall(pattern, text or "", re.IGNORECASE):
            value = clean_value(match)
            if not value:
                continue
            digits = compact_digits(value)
            if 8 <= len(digits) <= 12 and value not in cleaned:
                cleaned.append(value)

    return cleaned


def extract_phone(text: str):
    patterns = [
        r"(?:PBX|TEL[EÉ]FONO|TEL|CELULAR|CEL|M[OÓ]VIL|CONTACTO)\s*[:\-]?\s*([\d\+\-\(\) ]{7,})",
        r"(\(\+?\d{1,3}\)\s*\d[\d\-\s]{6,})",
        r"(\+?\d[\d\-\s]{7,})",
    ]
    for pattern in patterns:
        match = re.search(pattern, text or "", re.IGNORECASE)
        if match:
            return clean_value(match.group(1))
    return None


def extract_address(text: str):
    patterns = [
        r"(?:Direcci[oó]n|Direccion|Domicilio|Sede|Address)\s*[:\-]\s*(.+)",
        r"(?:Av\.?|Avenida|Calle|Cl\.?|CLL|Carrera|Cra\.?|CR|Kr|Diagonal|Diag\.?|Transversal|Tv\.?)\s+[^\n]{6,}",
    ]

    for pattern in patterns:
        match = re.search(pattern, text or "", re.IGNORECASE)
        if match:
            value = clean_value(match.group(1) if match.lastindex else match.group(0))
            if value and len(value) >= 8:
                return value

    return None


def extract_city(text: str):
    patterns = [
        r"(?:Ciudad|Municipio|Ubicaci[oó]n|Lugar de expedici[oó]n)\s*[:\-]\s*(.+)",
    ]
    for pattern in patterns:
        match = re.search(pattern, text or "", re.IGNORECASE)
        if match:
            value = clean_value(match.group(1))
            if value:
                return value

    # fallback suave
    lines = [clean_value(x) for x in (text or "").splitlines() if clean_value(x)]
    city_keywords = ["BOGOT", "MEDELL", "CALI", "BARRANQUILLA", "CARTAGENA", "D.C.", "CUNDINAMARCA"]
    for line in lines:
        upper = normalize_text(line)
        if any(k in upper for k in city_keywords):
            return line

    return None


def infer_person_type(empresa: str | None):
    if not empresa:
        return None

    upper = empresa.upper()
    juridico_keywords = [
        "SAS", "S.A.", "LTDA", "S EN C", "S.A.S", "S A S", "S.A", "SAS.",
        "E.S.P", "ESP", "SUCURSAL", "INC", "LLC", "CORP"
    ]
    if any(keyword in upper for keyword in juridico_keywords):
        return 2

    return 1


def infer_contribution_type(text: str):
    upper = normalize_text(text)

    if "GRAN CONTRIBUYENTE" in upper:
        return 3
    if "REGIMEN SIMPLE" in upper or "RÉGIMEN SIMPLE" in upper:
        return 4
    if "RESPONSABLE DE IVA" in upper or "RESPONSABLES DE IVA" in upper or "IMPUESTO SOBRE LAS VENTAS" in upper:
        return 1
    if "NO RESPONSABLE DE IVA" in upper:
        return 0
    if "EXENTO" in upper:
        return 5

    return None


def infer_retention_type(text: str):
    upper = normalize_text(text)

    if "AUTORRETENEDOR" in upper or "AUTORRETENEDORES" in upper:
        return 3
    if "EXENTO DE RETENCION" in upper or "EXENTO DE RETENCIÓN" in upper:
        return 1
    if (
        "AGENTE RETENEDOR" in upper
        or "AGENTES RETENEDORES" in upper
        or "RETENCION EN LA FUENTE" in upper
        or "RETENCIÓN EN LA FUENTE" in upper
    ):
        return 2

    return 0


def infer_state_enterprise_type(text: str):
    upper = normalize_text(text)

    if "EMPRESA ESTATAL" not in upper and "ESTATAL" not in upper:
        return 0
    if "MUNICIPAL" in upper:
        return 1
    if "DEPARTAMENTAL" in upper:
        return 2
    if "DISTRITAL" in upper:
        return 3

    return 0


def infer_electronic_biller(text: str):
    upper = normalize_text(text)
    if "FACTURA ELECTRONICA" in upper or "FACTURA ELECTRÓNICA" in upper or "BILLETE DE TRANSPORTE AEREO ELECTRONICO" in upper:
        return 1
    return None


def _line_is_company_candidate(line: str) -> bool:
    if not line or len(line) < 4:
        return False

    upper = normalize_text(line)

    if any(stop in upper for stop in COMPANY_STOPWORDS):
        return False

    # evitar líneas que son casi solo números o metadata
    digits = compact_digits(line)
    if digits and len(digits) >= max(6, len(line) // 2):
        return False

    return True


def extract_company_candidates(text: str) -> list[str]:
    lines = [clean_value(line) for line in (text or "").splitlines() if clean_value(line)]
    candidates = []

    explicit_patterns = [
        r"Raz[oó]n Social\s*[:\-]\s*(.+)",
        r"Nombre\/Raz[oó]n Social\s*[:\-]\s*(.+)",
        r"Proveedor\s*[:\-]\s*(.+)",
        r"Emisor\s*[:\-]\s*(.+)",
        r"Prestador\s*[:\-]\s*(.+)",
        r"Empresa\s*[:\-]\s*(.+)",
        r"Nombre y\/o Raz[oó]n Social del Emisor\s*[:\-]\s*(.+)",
    ]

    for pattern in explicit_patterns:
        match = re.search(pattern, text or "", re.IGNORECASE)
        if match:
            value = clean_value(match.group(1))
            if value:
                candidates.append(value)

    # patrones directos que en tus pruebas salieron mejor para facturas reales
    direct_patterns = [
        r"EMPRESA DE TELECOMUNICACIONES DE BOGOTA.*?ETB",
        r"ETB\s+S\.?A\.?\s*E\.?S\.?P\.?",
        r"AEROVIAS DE INTEGRACI[OÓ]N REGIONAL S\.?A\.?",
        r"LATAM AIRLINES",
        r"COLOMBIA TELECOMUNICACIONES?.*?S\.?A\.?",
        r"COMCEL S\.?A\.?",
        r"VANTI S\.?A\.?\s*E\.?S\.?P\.?",
        r"NETSERVER COMPUTADORES S\.?A\.?\s*S\.?",
    ]
    upper_text = normalize_text(text)
    for pattern in direct_patterns:
        match = re.search(pattern, upper_text, re.IGNORECASE)
        if match:
            value = clean_value(match.group(0))
            if value:
                candidates.append(value)

    # top-left / primeras líneas
    for line in lines[:18]:
        if _line_is_company_candidate(line):
            candidates.append(line)

    dedup = []
    seen = set()
    for cand in candidates:
        key = normalize_text(cand)
        if key and key not in seen:
            seen.add(key)
            dedup.append(cand)

    return dedup


def extract_customer_entity(text: str) -> dict | None:
    customer_name = None
    customer_nit = None
    customer_email = None

    customer_patterns = [
        r"Nombre y\/o Raz[oó]n Social del Adquiriente\s*[:\-]\s*(.+)",
        r"Cliente\s*[:\-]\s*(.+)",
        r"Adquiriente\s*[:\-]\s*(.+)",
        r"Comprador\s*[:\-]\s*(.+)",
        r"Señores\s*[:\-]\s*(.+)",
    ]
    for pattern in customer_patterns:
        match = re.search(pattern, text or "", re.IGNORECASE)
        if match:
            customer_name = clean_value(match.group(1))
            break

    nit_patterns = [
        r"NIT Cliente\s*[:\-]?\s*([0-9.\- ]{8,20})",
        r"NIT Adquiriente\s*[:\-]?\s*([0-9.\- ]{8,20})",
        r"NIT Comprador\s*[:\-]?\s*([0-9.\- ]{8,20})",
        r"N[uú]mero de Identificaci[oó]n y\/o NIT\s*[:\-]?\s*([0-9.\- ]{8,20})",
    ]
    for pattern in nit_patterns:
        match = re.search(pattern, text or "", re.IGNORECASE)
        if match:
            customer_nit = clean_value(match.group(1))
            break

    email_patterns = [
        r"E-?Mail\s*[:\-]\s*([A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,})",
    ]
    for pattern in email_patterns:
        match = re.search(pattern, text or "", re.IGNORECASE)
        if match:
            customer_email = clean_value(match.group(1))
            break

    if customer_name or customer_nit or customer_email:
        return {
            "nit": customer_nit,
            "empresa": customer_name,
            "person_type": infer_person_type(customer_name),
            "retention_type": None,
            "contribution_type": None,
            "state_enterprise_type": None,
            "electronic_biller": None,
            "direccion": None,
            "cod_ciudad": None,
            "ubicacion": None,
            "telefono": None,
            "email_rut": customer_email,
            "fuente": "factura",
            "rol_documento": "cliente",
        }

    return None


def parse_factura_entities(text: str) -> list[dict]:
    entities = []

    lines = [line.strip() for line in (text or "").splitlines() if line.strip()]
    nits = extract_nits(text)
    emails = extract_emails(text)
    telefono = extract_phone(text)
    direccion = extract_address(text)
    ciudad = extract_city(text)
    company_candidates = extract_company_candidates(text)

    empresa_principal = company_candidates[0] if company_candidates else None
    nit_principal = nits[0] if nits else None
    email_principal = emails[0] if emails else None

    # Evita quedarse con líneas técnicas como "Generated by ..."
    if empresa_principal and any(x in normalize_text(empresa_principal) for x in ["GENERATED BY", "SIGNATURE", "SOFTWARE", "GOSOCKET", "SOUTH CONSULTING"]):
        empresa_principal = company_candidates[1] if len(company_candidates) > 1 else None

    if empresa_principal or nit_principal or email_principal or direccion:
        entities.append({
            "nit": nit_principal,
            "empresa": empresa_principal,
            "person_type": infer_person_type(empresa_principal),
            "retention_type": infer_retention_type(text),
            "contribution_type": infer_contribution_type(text),
            "state_enterprise_type": infer_state_enterprise_type(text),
            "electronic_biller": infer_electronic_biller(text),
            "direccion": direccion,
            "cod_ciudad": None,
            "ubicacion": ciudad,
            "telefono": telefono,
            "email_rut": email_principal,
            "fuente": "factura",
            "rol_documento": "emisor",
        })

    customer_entity = extract_customer_entity(text)
    if customer_entity:
        entities.append(customer_entity)

    return deduplicate_entities(entities)


def deduplicate_entities(entities: list[dict]) -> list[dict]:
    result = []
    seen = set()

    for entity in entities:
        key = (
            normalize_text(entity.get("empresa")),
            compact_digits(entity.get("nit")),
            normalize_text(entity.get("rol_documento")),
        )
        if key in seen:
            continue
        seen.add(key)
        result.append(entity)

    return result