"""
MiniAgent: orchestrates extraction per document.
Supports execution modes (fast/balanced/deep), early stop,
lazy GPT (only when confidence is insufficient), and caching.

Adjusted to improve recall:
- GPT enters when regex extraction is weak OR no match exists
- no longer depends only on one confidence function
- keeps RUT analysis untouched
"""
from __future__ import annotations

import logging

from src.agents.gpt_client import GPTBudget, extract_with_gpt_entities
from src.cache.cache_manager import CacheManager
from src.extraction.pdf_reader import extract_text_smart
from src.matching.proveedor_matcher import match_proveedor
from src.parsing.factura_parser import parse_factura_entities
from src.parsing.rut_parser import parse_rut

logger = logging.getLogger("mini_agent")


class MiniAgent:
    def __init__(
        self,
        mode: str = "balanced",
        gpt_budget: GPTBudget | None = None,
        cache: CacheManager | None = None,
    ):
        self.mode = mode
        self.gpt_budget = gpt_budget
        self.cache = cache

    def detect_document_type(self, text: str, path: str = "") -> str:
        upper_text = (text or "").upper()
        upper_path = (path or "").upper()

        rut_keywords = [
            "REGISTRO UNICO TRIBUTARIO",
            "REGISTRO ÚNICO TRIBUTARIO",
            "FORMULARIO DEL RUT",
        ]
        if any(keyword in upper_text for keyword in rut_keywords):
            return "rut"

        if "RUT" in upper_path and "FACTURA" not in upper_path and "FRA" not in upper_path:
            return "rut"

        factura_keywords = [
            "FACTURA",
            "FACTURA ELECTRONICA",
            "FACTURA ELECTRÓNICA",
            "INVOICE",
            "CUFE",
            "CUDE",
            "ADQUIRIENTE",
            "SEÑORES",
            "RESOLUCION DIAN",
            "NUMERO DE FACTURA",
            "NÚMERO DE FACTURA",
            "CUENTA DE COBRO",
            "RECIBO",
            "TOTAL A PAGAR",
            "SUBTOTAL",
            "IVA",
            "BASE GRAVABLE",
            "VALOR TOTAL",
            "FECHA DE VENCIMIENTO",
            "FORMA DE PAGO",
            "REFERENCIA DE PAGO",
            "PERIODO FACTURADO",
            "BILLETE DE TRANSPORTE AEREO",
            "BILLETE DE TRANSPORTE AÉREO",
        ]
        if any(keyword in upper_text for keyword in factura_keywords):
            return "factura"

        file_keywords = [
            "FRA",
            "FACTURA",
            "INVOICE",
            "FE-",
            "FC-",
            "FV-",
            "TQT-",
            "COO-",
            "PTC",
            "CER-",
            "GNFR-",
            "REF",
            "FACT",
        ]
        if any(keyword in upper_path for keyword in file_keywords):
            return "factura"

        if any(keyword in upper_text for keyword in ["NIT", "DIRECCION", "DIRECCIÓN"]):
            return "factura"

        return "documento"

    def _extract_regex(self, text: str, doc_type: str) -> list[dict]:
        if doc_type == "rut":
            entity = parse_rut(text)
            return [entity] if entity else []

        if doc_type in ("factura", "documento"):
            return parse_factura_entities(text)

        return []

    def _select_text_for_gpt(self, text: str) -> str:
        lines = [line for line in (text or "").splitlines() if line.strip()]
        if len(lines) <= 150:
            return text[:6000]

        positive_keywords = [
            "NIT", "RAZÓN SOCIAL", "RAZON SOCIAL", "CLIENTE", "ADQUIRIENTE",
            "DIRECCIÓN", "DIRECCION", "CIUDAD", "TEL", "TELÉFONO", "PBX",
            "FACTURA", "INVOICE", "RESPONSABLE", "IVA", "RÉGIMEN", "REGIMEN",
            "FACTURADOR ELECTRÓNICO", "FACTURADOR ELECTRONICO",
        ]
        negative_keywords = [
            "REVISOR FISCAL", "CONTADOR", "REPRESENTANTE LEGAL", "SOCIOS",
            "GENERATED BY", "SIGNATURE", "SOFTWARE", "GOSOCKET", "PWC",
            "CERTIFICACIÓN", "CERTIFICACION", "INFORME DEL REVISOR",
        ]

        block_size = 30
        scored_blocks: list[tuple[int, str]] = []

        for index in range(0, len(lines), block_size):
            block = "\n".join(lines[index:index + block_size])
            upper_block = block.upper()

            score = 0
            score += sum(2 for keyword in positive_keywords if keyword in upper_block)
            score -= sum(3 for keyword in negative_keywords if keyword in upper_block)

            if "@" in block:
                score += 1
            if "NIT" in upper_block:
                score += 2

            scored_blocks.append((score, block))

        scored_blocks.sort(key=lambda item: item[0], reverse=True)
        selected_blocks = [block for score, block in scored_blocks[:5] if score >= 0]

        if not selected_blocks:
            selected_blocks = [block for _, block in scored_blocks[:3]]

        return "\n\n".join(selected_blocks)[:6000]

    def _is_useful_entity(self, entity: dict | None) -> bool:
        if not entity:
            return False
        return bool(
            entity.get("empresa")
            or entity.get("nit")
            or entity.get("email_rut")
            or entity.get("direccion")
        )

    def _count_useful_fields(self, entity: dict | None) -> int:
        if not entity:
            return 0

        keys = [
            "empresa",
            "nit",
            "direccion",
            "ubicacion",
            "telefono",
            "email_rut",
            "person_type",
            "retention_type",
            "contribution_type",
            "electronic_biller",
        ]
        return sum(1 for key in keys if entity.get(key) not in (None, ""))

    def _entity_match_index(self, df, entity: dict) -> int | None:
        if df is None or not entity:
            return None
        try:
            return match_proveedor(df, entity)
        except Exception as error:
            logger.warning("Error haciendo match de entidad %s: %s", entity, error)
            return None

    def _find_best_regex_entity(self, entities: list[dict], df=None) -> tuple[dict | None, int | None]:
        if not entities:
            return None, None

        best_entity = None
        best_match_idx = None
        best_score = -1

        for entity in entities:
            match_idx = self._entity_match_index(df, entity)
            useful_count = self._count_useful_fields(entity)

            score = useful_count
            if match_idx is not None:
                score += 100

            if score > best_score:
                best_score = score
                best_entity = entity
                best_match_idx = match_idx

        return best_entity, best_match_idx

    def _should_use_gpt(
        self,
        doc_type: str,
        regex_entities: list[dict],
        best_entity: dict | None,
        best_match_idx: int | None,
        meta: dict | None = None,
    ) -> tuple[bool, str]:
        if self.mode not in ("balanced", "deep"):
            return False, "modo_no_permite_gpt"

        if self.gpt_budget is not None and not self.gpt_budget.can_call():
            return False, "sin_presupuesto_gpt"

        if not regex_entities:
            return True, "sin_entidades_regex"

        useful_count = self._count_useful_fields(best_entity)

        if best_match_idx is not None and useful_count >= 3:
            return False, "match_fuerte_regex"

        if doc_type == "documento":
            return True, "tipo_documento_desconocido"

        if best_match_idx is None:
            return True, "sin_match_excel"

        if not best_entity:
            return True, "sin_mejor_entidad"

        if not best_entity.get("nit"):
            return True, "sin_nit"

        if not best_entity.get("empresa"):
            return True, "sin_empresa"

        if useful_count < 3:
            return True, "pocos_campos_utiles"

        if meta and meta.get("method") in ("ocr_full", "ocr_useful_pages") and useful_count < 5:
            return True, "ocr_debil"

        return False, "regex_suficiente"

    def _merge_entity(self, base: dict, supplement: dict) -> dict:
        merged = dict(base)

        for key, value in (supplement or {}).items():
            if key in ("fuente", "rol_documento", "source_file", "document_type"):
                continue

            existing = merged.get(key)

            if existing is None:
                merged[key] = value
                continue

            if isinstance(existing, str) and not existing.strip():
                merged[key] = value
                continue

        return merged

    def _merge_entities(self, regex_entities: list[dict], gpt_entities: list[dict]) -> list[dict]:
        if regex_entities and not gpt_entities:
            return regex_entities

        if gpt_entities and not regex_entities:
            return gpt_entities

        if not regex_entities and not gpt_entities:
            return []

        final_entities = []
        used_gpt_indices = set()

        for regex_entity in regex_entities:
            best_index = None
            best_score = -1

            regex_name = (regex_entity.get("empresa") or "").strip().upper()
            regex_nit = (regex_entity.get("nit") or "").replace(".", "").replace("-", "").strip()

            for index, gpt_entity in enumerate(gpt_entities):
                if index in used_gpt_indices:
                    continue

                score = 0
                gpt_name = (gpt_entity.get("empresa") or "").strip().upper()
                gpt_nit = (gpt_entity.get("nit") or "").replace(".", "").replace("-", "").strip()

                if regex_nit and gpt_nit:
                    if regex_nit == gpt_nit:
                        score += 100
                    elif regex_nit in gpt_nit or gpt_nit in regex_nit:
                        score += 80

                if regex_name and gpt_name:
                    if regex_name == gpt_name:
                        score += 50
                    elif regex_name in gpt_name or gpt_name in regex_name:
                        score += 35

                if score > best_score:
                    best_score = score
                    best_index = index

            if best_index is not None and best_score >= 35:
                merged = self._merge_entity(regex_entity, gpt_entities[best_index])
                used_gpt_indices.add(best_index)
                final_entities.append(merged)
            else:
                final_entities.append(regex_entity)

        for index, gpt_entity in enumerate(gpt_entities):
            if index not in used_gpt_indices:
                final_entities.append(gpt_entity)

        return final_entities

    def _save_cache(self, file_hash: str | None, entities: list[dict], meta: dict | None = None):
        if self.cache and file_hash:
            self.cache.save(
                file_hash,
                {
                    "entities": entities,
                    "meta": meta or {},
                },
            )

    def process_file(self, path: str, df=None) -> list[dict]:
        file_hash = None
        if self.cache:
            file_hash = self.cache.get_hash(path)
            cached = self.cache.load(file_hash)
            if cached and cached.get("entities"):
                logger.info("Cache hit: %s", path)
                return cached["entities"]

        text, meta = extract_text_smart(path, mode=self.mode)

        if not text or len(text.strip()) < 20:
            logger.info("Ignorado: texto insuficiente (%s)", path)
            self._save_cache(file_hash, [], meta)
            return []

        doc_type = self.detect_document_type(text, path)

        regex_entities = self._extract_regex(text, doc_type)
        useful_regex = [entity for entity in regex_entities if self._is_useful_entity(entity)]

        best_regex_entity, best_match_idx = self._find_best_regex_entity(useful_regex, df=df)

        use_gpt, reason = self._should_use_gpt(
            doc_type=doc_type,
            regex_entities=useful_regex,
            best_entity=best_regex_entity,
            best_match_idx=best_match_idx,
            meta=meta,
        )

        # Early stop real
        if not use_gpt and useful_regex:
            logger.info("Early stop sin GPT (%s) motivo=%s", path, reason)

            for entity in useful_regex:
                entity["source_file"] = path
                entity["document_type"] = doc_type

            self._save_cache(file_hash, useful_regex, meta)
            return useful_regex

        gpt_entities: list[dict] = []

        if use_gpt:
            try:
                gpt_text = self._select_text_for_gpt(text)
                gpt_entities = extract_with_gpt_entities(gpt_text, budget=self.gpt_budget) or []
                logger.info("GPT invocado para: %s motivo=%s", path, reason)
            except Exception as error:
                logger.warning("GPT falló para %s: %s", path, error)
                gpt_entities = []

        final_entities = self._merge_entities(useful_regex, gpt_entities)
        result = [entity for entity in final_entities if self._is_useful_entity(entity)]

        for entity in result:
            entity["source_file"] = path
            entity["document_type"] = doc_type

        if not result:
            logger.info("Sin datos útiles: %s", path)
            self._save_cache(file_hash, [], meta)
            return []

        self._save_cache(file_hash, result, meta)
        return result