"""
Scores each page of a PDF to decide which ones are worth OCR-ing.
High-scoring pages contain useful business data.
Negative-scoring pages contain boilerplate (signatures, auditor info, etc.).
"""


POSITIVE_KEYWORDS = {
    "NIT": 3,
    "N.I.T": 3,
    "RAZON SOCIAL": 3,
    "RAZÓN SOCIAL": 3,
    "IDENTIFICACION": 3,
    "IDENTIFICACIÓN": 3,
    "DIRECCION": 2,
    "DIRECCIÓN": 2,
    "DOMICILIO": 2,
    "EMAIL": 2,
    "CORREO": 2,
    "FACTURA": 2,
    "INVOICE": 2,
    "CUENTA DE COBRO": 2,
    "CLIENTE": 2,
    "ADQUIRIENTE": 2,
    "TELEFONO": 2,
    "TELÉFONO": 2,
    "PBX": 2,
    "TOTAL": 1,
    "SUBTOTAL": 1,
    "IVA": 1,
    "REGISTRO UNICO TRIBUTARIO": 3,
    "RUT": 2,
}

NEGATIVE_KEYWORDS = {
    "REVISOR FISCAL": -3,
    "CONTADOR": -3,
    "REPRESENTANTE LEGAL": -3,
    "SOCIOS": -3,
    "JUNTA DIRECTIVA": -3,
    "JUNTA": -3,
    "GENERATED BY": -3,
    "SOFTWARE": -3,
    "SIGNATURE": -3,
    "CERTIFICACIÓN": -3,
    "CERTIFICACION": -3,
    "INFORME DEL REVISOR": -3,
    "DICTAMEN": -3,
    "NOTAS A LOS ESTADOS FINANCIEROS": -3,
    "BALANCE GENERAL": -2,
    "ESTADO DE RESULTADOS": -2,
}


def score_page(text: str) -> int:
    if not text:
        return 0
    upper = text.upper()
    score = 0
    for keyword, points in POSITIVE_KEYWORDS.items():
        if keyword in upper:
            score += points
    for keyword, points in NEGATIVE_KEYWORDS.items():
        if keyword in upper:
            score += points
    return score


def rank_pages(pages_text: list[str], threshold: int = 2) -> list[int]:
    """
    Returns indices of pages worth OCR-ing, sorted by score descending.
    Only includes pages with score >= threshold.
    """
    scored = [(i, score_page(text)) for i, text in enumerate(pages_text)]
    useful = [(i, s) for i, s in scored if s >= threshold]
    useful.sort(key=lambda x: x[1], reverse=True)
    return [i for i, _ in useful]


def find_pages_needing_ocr(pages_text: list[str], min_text_len: int = 40) -> list[int]:
    """
    Pages that have very little embedded text and might need OCR.
    Returns indices of pages with insufficient text.
    """
    return [
        i for i, text in enumerate(pages_text)
        if len((text or "").strip()) < min_text_len
    ]
